# Generated by Django 5.2.7 on 2025-12-13 11:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Auto-generated unique registration identifier', primary_key=True, serialize=False)),
                ('student_name', models.CharField(help_text='Full name of the student', max_length=200)),
                ('student_email', models.EmailField(help_text="Student's email address for communication", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date_of_birth', models.DateField(help_text="Student's date of birth")),
                ('grade', models.CharField(help_text='Current grade/class of the student', max_length=10)),
                ('school_name', models.CharField(help_text='Name of the school student is currently attending', max_length=300)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('telugu', 'Telugu'), ('both', 'Both')], default='english', help_text='Preferred language for learning content', max_length=20)),
                ('parent_name', models.CharField(help_text='Full name of parent or guardian', max_length=200)),
                ('parent_email', models.EmailField(help_text='Parent/guardian email for notifications', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Contact phone number (10 digits)', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('address', models.TextField(help_text='Complete residential address')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text='State name', max_length=100)),
                ('pincode', models.CharField(help_text='Postal pincode (6 digits)', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits', regex='^\\d{6}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of registration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when registration was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when registration was approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved the registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='student_reg_status_886550_idx'), models.Index(fields=['student_email'], name='student_reg_student_07f8e1_idx')],
            },
        ),
    ]
