# Generated by Django 5.2.7 on 2026-02-20 05:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
        ('read_along_service', '0003_remove_readalongsession_unique_read_along_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=15)),
                ('fluency_star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sessions', to='read_along_service.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sessions', to='auth_service.student')),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('student', 'language', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('frequency_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)])),
                ('word', models.CharField(max_length=100)),
                ('romanization', models.CharField(blank=True, default='', max_length=150)),
                ('word_type', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('number', 'Number'), ('conjunction', 'Conjunction'), ('other', 'Other')], default='other', max_length=20)),
                ('image_keyword', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to='read_along_service.language')),
            ],
            options={
                'ordering': ['grade', 'frequency_rank'],
            },
        ),
        migrations.CreateModel(
            name='StudentWordProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unseen', 'Unseen'), ('introduced', 'Introduced'), ('practicing', 'Practicing'), ('mastered', 'Mastered')], default='unseen', max_length=15)),
                ('exposure_count', models.IntegerField(default=0)),
                ('best_pronunciation_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mcq_correct_count', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to='auth_service.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocabulary_service.vocabularyword')),
            ],
        ),
        migrations.CreateModel(
            name='SessionWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pronunciation_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mcq_answered', models.BooleanField(default=False)),
                ('mcq_correct', models.BooleanField(default=False)),
                ('time_on_word_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_words', to='vocabulary_service.vocabularysession')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_words', to='vocabulary_service.vocabularyword')),
            ],
            options={
                'ordering': ['word_order'],
            },
        ),
        migrations.CreateModel(
            name='WordContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('example_translation', models.TextField()),
                ('mnemonic', models.TextField(blank=True, default='')),
                ('llm_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother_tongue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_contents', to='read_along_service.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='vocabulary_service.vocabularyword')),
            ],
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['language', 'grade', 'frequency_rank'], name='vocabulary__languag_dc4ff0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularyword',
            unique_together={('language', 'grade', 'frequency_rank')},
        ),
        migrations.AlterUniqueTogether(
            name='studentwordprogress',
            unique_together={('student', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionword',
            unique_together={('session', 'word')},
        ),
        migrations.AlterUniqueTogether(
            name='wordcontent',
            unique_together={('word', 'mother_tongue')},
        ),
    ]
