"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 2026-02-06: Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 2026-02-06: Secret key loaded from environment variable
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-in-production')

# 2026-02-06: Debug mode loaded from environment variable
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# 2025-10-31: CORS settings for React frontend
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ALLOW_CREDENTIALS = True

# Add these lines to your existing CORS settings in backend/settings.py
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow credentials (cookies, HTTP authentication) to be included in cross-site requests
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 2025-10-31: Third-party apps
    'rest_framework',
    'corsheaders',
    # 2025-10-31: BabySteps apps
    'services.curriculum_loader_service',
    'services.mentor_chat_service',
    'services.analytics_service',
    'services.llm_service',  # 2025-12-11: Generic LLM provider abstraction
    'student_registration',  # 2025-12-13: Student registration and approval workflow
    'services.learning_engine',  # 2025-12-18: Micro-lesson learning system
    'rest_framework_simplejwt',  # 2026-02-12: JWT authentication
    'services.auth_service',  # 2026-02-12: Authentication module (BS-AUT)
    'services.diagnostic_service',  # 2026-02-12: Diagnostic assessment module (BS-DIA)
    'services.teaching_engine',  # 2026-02-17: AI Teaching Engine module (BS-AIE)
    'services.parent_dashboard',  # 2026-02-19: Parent Dashboard module (BS-PAR)
    'services.read_along_service',  # 2026-02-19: Read-Along & Mimic Engine (BS-RAM)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 2025-10-31: CORS middleware must be before CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 2025-10-31: REST Framework settings
# 2025-12-12: Added pagination configuration for analytics API
# 2025-12-13: Updated authentication to return 401 for unauthenticated
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 2026-02-12: JWT auth
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 2025-12-12: Allow any by default, check in views
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # 2025-12-12: Default page size for all APIs
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'UNAUTHENTICATED_USER': None,  # 2025-12-13: Return 401 for unauthenticated instead of 403
}

# 2025-10-31: Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'services.curriculum_loader_service': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# 2025-12-11: LLM Provider Configuration
# Generic abstraction layer for easy provider switching

# Which LLM provider to use: 'ollama', 'openai', 'anthropic', 'google'
LLM_PROVIDER = 'ollama'

# Provider-specific configuration
LLM_CONFIG = {
    # Ollama settings (default)
    'model_name': 'llama3.2',
    'base_url': 'http://127.0.0.1:11434',
    'timeout': 120,
    'max_retries': 3,
}

# To switch to OpenAI (example):
# LLM_PROVIDER = 'openai'
# LLM_CONFIG = {
#     'model_name': 'gpt-3.5-turbo',
#     'api_key': os.getenv('OPENAI_API_KEY'),  # Set in environment
#     'timeout': 60,
# }

# To switch to Anthropic Claude (example):
# LLM_PROVIDER = 'anthropic'
# LLM_CONFIG = {
#     'model_name': 'claude-3-sonnet-20240229',
#     'api_key': os.getenv('ANTHROPIC_API_KEY'),  # Set in environment
#     'timeout': 60,
# }

# 2026-02-12: JWT Configuration (SimpleJWT)
from datetime import timedelta  # noqa: E402
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# 2026-02-12: OTP Provider Configuration
# Which OTP provider to use: 'mock', 'twilio', 'gupshup'
OTP_PROVIDER = os.getenv('OTP_PROVIDER', 'mock')

OTP_CONFIG = {
    'otp_length': 6,
    'otp_expiry_minutes': 10,
    'max_attempts': 3,
    'cooldown_seconds': 10,  # 2026-02-12: Short cooldown for dev (increase for production)
}

# Twilio settings (for production WhatsApp OTP)
# OTP_PROVIDER = 'twilio'
# TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
# TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
# TWILIO_WHATSAPP_FROM = os.getenv('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')
