# Generated by Django 5.2.7 on 2026-03-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('pod_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='podenrollment',
            name='unique_pod_student',
        ),
        migrations.AlterUniqueTogether(
            name='podenrollment',
            unique_together={('pod', 'student')},
        ),
    ]
