# Generated by Django 5.2.7 on 2025-12-11 15:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this activity record', primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lesson_view', 'Lesson View'), ('lesson_complete', 'Lesson Complete'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_complete', 'Quiz Complete'), ('practice', 'Practice Exercise'), ('video_watch', 'Video Watch'), ('reading', 'Reading Activity'), ('mentor_chat', 'Mentor Chat'), ('assessment', 'Assessment'), ('game', 'Educational Game')], db_index=True, help_text='Type of learning activity', max_length=50)),
                ('content_id', models.CharField(help_text='Identifier of the content (lesson ID, video ID, etc.)', max_length=255)),
                ('content_type', models.CharField(help_text='Type of content (lesson, video, quiz, etc.)', max_length=100)),
                ('started_at', models.DateTimeField(db_index=True, help_text='When the activity started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the activity ended (null if ongoing)', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration of activity in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the activity was completed')),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, help_text='Engagement score from 0 to 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data (interactions, clicks, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('student', models.ForeignKey(help_text='Student who performed this activity', on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Activity',
                'verbose_name_plural': 'Student Activities',
                'db_table': 'analytics_student_activity',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', '-started_at'], name='activity_student_time_idx'), models.Index(fields=['content_type', 'content_id'], name='activity_content_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this progress record', primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('evs', 'Environmental Studies'), ('hindi', 'Hindi'), ('computer', 'Computer Science')], help_text='Subject area', max_length=50)),
                ('grade_level', models.IntegerField(help_text='Grade level (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('lessons_completed', models.IntegerField(default=0, help_text='Number of lessons completed', validators=[django.core.validators.MinValueValidator(0)])),
                ('lessons_total', models.IntegerField(default=0, help_text='Total lessons in curriculum', validators=[django.core.validators.MinValueValidator(0)])),
                ('skills_mastered', models.IntegerField(default=0, help_text='Number of skills mastered', validators=[django.core.validators.MinValueValidator(0)])),
                ('skills_total', models.IntegerField(default=0, help_text='Total skills in curriculum', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average score across all activities', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_date', models.DateField(blank=True, db_index=True, help_text='Date of last learning activity', null=True)),
                ('streak_days', models.IntegerField(default=0, help_text='Current consecutive days of learning', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('student', models.ForeignKey(help_text='Student whose progress is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress Records',
                'db_table': 'analytics_student_progress',
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['student', 'subject'], name='progress_student_subject_idx')],
                'unique_together': {('student', 'subject', 'grade_level')},
            },
        ),
    ]
