# Generated by Django 5.2.7 on 2025-12-11 16:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analytics_service.concept')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'analytics_concept',
                'ordering': ['subject', 'parent', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('difficulty', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='analytics_service.concept')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_skills', to='analytics_service.skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'analytics_skill',
                'ordering': ['subject', 'grade_level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StudentMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_level', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('practice_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('first_attempted', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='analytics_service.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Mastery',
                'verbose_name_plural': 'Student Masteries',
                'db_table': 'analytics_student_mastery',
                'ordering': ['-last_practiced'],
            },
        ),
        migrations.CreateModel(
            name='MasteryEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Test'), ('practice', 'Practice'), ('observation', 'Teacher Observation'), ('project', 'Project'), ('peer_review', 'Peer Review')], db_index=True, max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('assessment_id', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='analytics_service.studentmastery')),
            ],
            options={
                'verbose_name': 'Mastery Evidence',
                'verbose_name_plural': 'Mastery Evidence',
                'db_table': 'analytics_mastery_evidence',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['subject'], name='analytics_c_subject_f61f80_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['parent', 'order'], name='analytics_c_parent__b291cd_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['subject', 'grade_level'], name='analytics_s_subject_e0fb87_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='analytics_s_code_820d44_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['student', 'mastery_level'], name='analytics_s_student_d18a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['skill', 'mastery_level'], name='analytics_s_skill_i_93fd41_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['-last_practiced'], name='analytics_s_last_pr_4d9dd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmastery',
            unique_together={('student', 'skill')},
        ),
        migrations.AddIndex(
            model_name='masteryevidence',
            index=models.Index(fields=['mastery', '-recorded_at'], name='analytics_m_mastery_11f2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryevidence',
            index=models.Index(fields=['evidence_type'], name='analytics_m_evidenc_c03372_idx'),
        ),
    ]
