# Generated by Django 5.2.7 on 2025-12-11 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0002_concept_skill_studentmastery_masteryevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['subject', 'order', 'name'], 'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True, help_text='When session started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session ended', null=True)),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('grade_level', models.IntegerField(help_text='Grade level (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_duration_seconds', models.IntegerField(blank=True, help_text='Total session duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('break_duration_seconds', models.IntegerField(default=0, help_text='Time spent on breaks in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('interaction_count', models.IntegerField(default=0, help_text='Number of student interactions', validators=[django.core.validators.MinValueValidator(0)])),
                ('context_switches', models.IntegerField(default=0, help_text='Number of context/focus changes', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Session',
                'verbose_name_plural': 'Learning Sessions',
                'db_table': 'analytics_learning_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('attention_score', 'Attention Score'), ('participation_rate', 'Participation Rate'), ('comprehension_indicator', 'Comprehension Indicator'), ('motivation_level', 'Motivation Level'), ('distraction_index', 'Distraction Index')], db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Metric value (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confidence in metric calculation (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='analytics_service.learningsession')),
            ],
            options={
                'verbose_name': 'Engagement Metric',
                'verbose_name_plural': 'Engagement Metrics',
                'db_table': 'analytics_engagement_metric',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('question_answer', 'Question Answer'), ('video_watch', 'Video Watch'), ('reading', 'Reading'), ('practice', 'Practice Exercise'), ('quiz', 'Quiz'), ('discussion', 'Discussion'), ('break', 'Break')], db_index=True, max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('was_successful', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='analytics_service.learningsession')),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'db_table': 'analytics_session_activity',
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['student', '-started_at'], name='analytics_l_student_a35c68_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['subject'], name='analytics_l_subject_396529_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['is_completed'], name='analytics_l_is_comp_5fcc67_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementmetric',
            index=models.Index(fields=['session', 'metric_type'], name='analytics_e_session_b7256c_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementmetric',
            index=models.Index(fields=['metric_type'], name='analytics_e_metric__343452_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'started_at'], name='analytics_s_session_a34207_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['activity_type'], name='analytics_s_activit_417ff3_idx'),
        ),
    ]
