# Generated by Django 5.2.7 on 2025-12-11 16:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0003_alter_concept_options_learningsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStyleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visual_score', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Visual learning preference (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auditory_score', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Auditory learning preference (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kinesthetic_score', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Kinesthetic/hands-on preference (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reading_writing_score', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Reading/Writing preference (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sample_size', models.IntegerField(default=0, help_text='Number of observations')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Style Profile',
                'verbose_name_plural': 'Learning Style Profiles',
                'db_table': 'analytics_learning_style_profile',
            },
        ),
        migrations.CreateModel(
            name='ContentInteractionPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('video_rewatch', 'Video Rewatching'), ('pause_frequency', 'Content Pausing'), ('note_taking', 'Note Taking'), ('speed_adjustment', 'Playback Speed Changes'), ('skip_behavior', 'Content Skipping'), ('repetition_preference', 'Repetition Seeking')], db_index=True, max_length=50)),
                ('frequency', models.IntegerField(default=0, help_text='How often pattern occurs')),
                ('avg_duration_seconds', models.IntegerField(default=0, help_text='Average duration')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('first_observed', models.DateTimeField(auto_now_add=True)),
                ('last_observed', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction Pattern',
                'verbose_name_plural': 'Interaction Patterns',
                'db_table': 'analytics_interaction_pattern',
                'ordering': ['-last_observed'],
                'indexes': [models.Index(fields=['student', 'pattern_type'], name='analytics_i_student_7d3104_idx')],
            },
        ),
        migrations.CreateModel(
            name='StylePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text'), ('image', 'Image'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('game', 'Game')], db_index=True, max_length=50)),
                ('engagement_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_observations', to='analytics_service.learningsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style Preference',
                'verbose_name_plural': 'Style Preferences',
                'db_table': 'analytics_style_preference',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['student', 'content_type'], name='analytics_s_student_c987b0_idx'), models.Index(fields=['-recorded_at'], name='analytics_s_recorde_89f475_idx')],
            },
        ),
    ]
