# Generated by Django 5.2.7 on 2025-12-11 16:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0004_learningstyleprofile_contentinteractionpattern_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDifficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('exercise', 'Exercise'), ('video', 'Video'), ('reading', 'Reading')], max_length=50)),
                ('base_difficulty', models.DecimalField(decimal_places=2, help_text='Base difficulty rating (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cognitive_load', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Cognitive load required (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('complexity_score', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Content complexity (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prerequisite_weight', models.DecimalField(decimal_places=2, default=Decimal('20.0'), help_text='How much prerequisites affect difficulty', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Difficulty',
                'verbose_name_plural': 'Content Difficulties',
                'db_table': 'analytics_content_difficulty',
                'ordering': ['base_difficulty'],
                'indexes': [models.Index(fields=['content_type', 'base_difficulty'], name='analytics_c_content_230772_idx')],
            },
        ),
        migrations.CreateModel(
            name='DifficultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_difficulty', models.DecimalField(decimal_places=2, default=Decimal('50.0'), help_text='Current difficulty level (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_success_rate', models.DecimalField(decimal_places=2, default=Decimal('75.0'), help_text='Target success rate for optimal challenge', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('adjustment_speed', models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Speed of difficulty adjustment (0-20)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('last_adjusted', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_profiles', to='analytics_service.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Difficulty Profile',
                'verbose_name_plural': 'Difficulty Profiles',
                'db_table': 'analytics_difficulty_profile',
                'ordering': ['-last_adjusted'],
                'indexes': [models.Index(fields=['student', 'skill'], name='analytics_d_student_e494b1_idx')],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('successes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_time_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='analytics_service.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Snapshot',
                'verbose_name_plural': 'Performance Snapshots',
                'db_table': 'analytics_performance_snapshot',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['student', 'skill', '-recorded_at'], name='analytics_p_student_3f3a58_idx')],
            },
        ),
    ]
