# Generated by Django 5.2.7 on 2025-12-11 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0005_contentdifficulty_difficultyprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('essay', 'Essay')], db_index=True, max_length=50)),
                ('question_text', models.TextField(help_text='Question text')),
                ('correct_answer', models.TextField(help_text='Correct answer or key')),
                ('difficulty_level', models.DecimalField(decimal_places=2, help_text='Question difficulty (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('options', models.TextField(blank=True, help_text='JSON encoded options for MCQ', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for answer')),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('source_content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='How many times used')),
                ('avg_success_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average success rate on this question', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='analytics_service.skill')),
            ],
            options={
                'verbose_name': 'Assessment Question',
                'verbose_name_plural': 'Assessment Questions',
                'db_table': 'analytics_assessment_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('practice', 'Practice'), ('quiz', 'Quiz'), ('test', 'Test'), ('adaptive', 'Adaptive Assessment'), ('diagnostic', 'Diagnostic')], max_length=50)),
                ('target_question_count', models.IntegerField(default=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final average score', max_digits=5, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='analytics_service.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Session',
                'verbose_name_plural': 'Assessment Sessions',
                'db_table': 'analytics_assessment_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(max_length=50)),
                ('template_text', models.TextField(help_text='Template with {variables}')),
                ('variables', models.TextField(help_text='JSON definition of variables')),
                ('difficulty_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to='analytics_service.skill')),
            ],
            options={
                'verbose_name': 'Question Template',
                'verbose_name_plural': 'Question Templates',
                'db_table': 'analytics_question_template',
                'ordering': ['skill', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_answer', models.TextField(help_text="Student's answer")),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_taken_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated feedback', null=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics_service.assessmentquestion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics_service.assessmentsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Response',
                'verbose_name_plural': 'Student Responses',
                'db_table': 'analytics_student_response',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['skill', 'difficulty_level'], name='analytics_a_skill_i_f8ad38_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['question_type'], name='analytics_a_questio_31230d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['student', '-started_at'], name='analytics_a_student_279a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['skill', 'is_completed'], name='analytics_a_skill_i_393831_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['skill', 'is_active'], name='analytics_q_skill_i_379057_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['student', '-answered_at'], name='analytics_s_student_3a17c7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['question'], name='analytics_s_questio_ebcd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['session'], name='analytics_s_session_cc5c98_idx'),
        ),
    ]
