# Generated by Django 5.2.7 on 2025-12-11 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0006_assessmentquestion_assessmentsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
