# Generated by Django 5.2.7 on 2026-02-12 16:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0007_alter_studentresponse_time_taken_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(default='homework', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('total_points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('rubric', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_assignment',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='analytics_service.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_assignment_submission',
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_classroom',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='analytics_service.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_classroom_enrollment',
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=30)),
                ('resource_id', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_recommendations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_resource_recommendation',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_type', models.CharField(default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='analytics_service.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_student_group',
            },
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('note_type', models.CharField(default='observation', max_length=20)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_teacher_note',
            },
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='concept',
        ),
        migrations.DeleteModel(
            name='ContentDifficulty',
        ),
        migrations.RemoveField(
            model_name='contentinteractionpattern',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='difficultyprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='difficultyprofile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='difficultyprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='engagementmetric',
            name='session',
        ),
        migrations.RemoveField(
            model_name='learningsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='sessionactivity',
            name='session',
        ),
        migrations.RemoveField(
            model_name='stylepreference',
            name='session',
        ),
        migrations.RemoveField(
            model_name='learningstyleprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='masteryevidence',
            name='mastery',
        ),
        migrations.RemoveField(
            model_name='performancesnapshot',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='performancesnapshot',
            name='student',
        ),
        migrations.RemoveField(
            model_name='questiontemplate',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='studentmastery',
            name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='studentmastery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmastery',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='stylepreference',
            name='student',
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='activity_type',
            field=models.CharField(choices=[('lesson_view', 'Lesson View'), ('lesson_complete', 'Lesson Complete'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_complete', 'Quiz Complete'), ('practice', 'Practice Exercise'), ('video_watch', 'Video Watch'), ('reading', 'Reading Activity'), ('mentor_chat', 'Mentor Chat'), ('assessment', 'Assessment'), ('game', 'Educational Game')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='content_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='content_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='engagement_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='started_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='grade_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='last_activity_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='lessons_completed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='lessons_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='skills_mastered',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='skills_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='streak_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('evs', 'Environmental Studies'), ('hindi', 'Hindi'), ('computer', 'Computer Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='time_spent_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='analytics_service.classroom'),
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='AssessmentSession',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='ContentInteractionPattern',
        ),
        migrations.DeleteModel(
            name='DifficultyProfile',
        ),
        migrations.DeleteModel(
            name='EngagementMetric',
        ),
        migrations.DeleteModel(
            name='SessionActivity',
        ),
        migrations.DeleteModel(
            name='LearningSession',
        ),
        migrations.DeleteModel(
            name='LearningStyleProfile',
        ),
        migrations.DeleteModel(
            name='MasteryEvidence',
        ),
        migrations.DeleteModel(
            name='PerformanceSnapshot',
        ),
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='StudentMastery',
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
        migrations.DeleteModel(
            name='StylePreference',
        ),
    ]
