# Generated by Django 5.2.7 on 2025-12-18 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(help_text='Unique micro-lesson ID (e.g., MATH_C5_CH3_ML2)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Micro-lesson title', max_length=200)),
                ('learning_objective', models.TextField(help_text='Single, precise learning objective for this micro-lesson')),
                ('subject', models.CharField(help_text='Subject (Math, Science, English, etc.)', max_length=50)),
                ('class_number', models.IntegerField(help_text='Class/Grade number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('chapter_id', models.CharField(help_text='Chapter identifier', max_length=50)),
                ('chapter_name', models.CharField(help_text='Chapter name', max_length=200)),
                ('sequence_in_chapter', models.IntegerField(help_text='Order of this micro-lesson within the chapter', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.IntegerField(default=7, help_text='Expected duration in minutes (5-10)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('worked_examples', models.JSONField(default=list, help_text='Exactly 2 worked examples with step-by-step solutions')),
                ('practice_questions', models.JSONField(default=list, help_text='Exactly 10 practice questions')),
                ('practice_themes', models.JSONField(default=list, help_text='6-10 practice themes for varied application')),
                ('visual_assets', models.JSONField(default=list, help_text='Visual assets: concept intro, example-linked, misconception visuals')),
                ('teacher_narration', models.JSONField(default=dict, help_text='Narration scripts: support, core, challenge levels')),
                ('textbook_reading', models.JSONField(default=dict, help_text='Guided textbook reading section reference')),
                ('misconceptions', models.JSONField(default=list, help_text='Common misconceptions to address')),
                ('prerequisites', models.JSONField(default=list, help_text='List of prerequisite micro-lesson IDs')),
                ('qa_status', models.CharField(choices=[('pending', 'Pending Review'), ('passed', 'QA Passed'), ('failed', 'QA Failed'), ('revision', 'Under Revision')], default='pending', help_text='Academic QA status', max_length=20)),
                ('qa_passed_at', models.DateTimeField(blank=True, help_text='Timestamp when QA was passed', null=True)),
                ('qa_notes', models.TextField(blank=True, help_text='QA reviewer notes')),
                ('version', models.CharField(default='1.0', help_text='Lesson version for auditability', max_length=20)),
                ('language', models.CharField(default='en', help_text='Primary language code', max_length=20)),
                ('localization_variants', models.JSONField(blank=True, default=dict, help_text='Localized content variants (Telugu, Hindi, etc.)')),
                ('is_published', models.BooleanField(default=False, help_text='Whether lesson is published and visible to students')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Agent or user who created this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_microlessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Micro-Lesson',
                'verbose_name_plural': 'Micro-Lessons',
                'ordering': ['class_number', 'subject', 'chapter_id', 'sequence_in_chapter'],
            },
        ),
        migrations.CreateModel(
            name='MicroLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('mastered', 'Mastered')], default='not_started', help_text='Current progress status', max_length=20)),
                ('current_step', models.CharField(choices=[('objective', 'Viewing Objective'), ('visual_intro', 'Visual Introduction'), ('worked_example_1', 'Worked Example 1'), ('worked_example_2', 'Worked Example 2'), ('practice', 'Practice Questions'), ('mastery_check', 'Mastery Checkpoint'), ('completed', 'Completed')], default='objective', help_text='Current step in lesson flow', max_length=30)),
                ('questions_attempted', models.IntegerField(default=0, help_text='Number of practice questions attempted', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('questions_correct', models.IntegerField(default=0, help_text='Number of practice questions answered correctly', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('mastery_score', models.IntegerField(default=0, help_text='Mastery score percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Total time spent on this lesson in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('attempt_number', models.IntegerField(default=1, help_text='Which attempt this is (for retries)', validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.CharField(choices=[('support', 'Support Level'), ('core', 'Core Level'), ('challenge', 'Challenge Level')], default='core', help_text='Difficulty level student experienced', max_length=20)),
                ('hints_used', models.IntegerField(default=0, help_text='Number of hints requested', validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(blank=True, help_text='When student started this lesson', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When student completed this lesson', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('micro_lesson', models.ForeignKey(help_text='The micro-lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning_engine.microlesson')),
                ('student', models.ForeignKey(help_text='Student taking the lesson', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Micro-Lesson Progress',
                'verbose_name_plural': 'Micro-Lesson Progress Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField(help_text='Question number (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('question_content', models.JSONField(help_text='Snapshot of question at time of attempt')),
                ('student_answer', models.TextField(help_text="Student's submitted answer")),
                ('correct_answer', models.TextField(help_text='The correct answer')),
                ('is_correct', models.BooleanField(help_text='Whether the answer was correct')),
                ('partial_credit', models.FloatField(default=0.0, help_text='Partial credit awarded (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('time_taken_seconds', models.IntegerField(help_text='Time taken to answer in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('hints_used', models.IntegerField(default=0, help_text='Number of hints used for this question', validators=[django.core.validators.MinValueValidator(0)])),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retries for this question', validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback_shown', models.JSONField(blank=True, default=dict, help_text='Feedback displayed to student')),
                ('misconception_detected', models.CharField(blank=True, help_text='Misconception identified from wrong answer', max_length=200)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_progress', models.ForeignKey(help_text='Associated lesson progress record', on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='learning_engine.microlessonprogress')),
            ],
            options={
                'verbose_name': 'Practice Attempt',
                'verbose_name_plural': 'Practice Attempts',
                'ordering': ['lesson_progress', 'question_index', 'attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_speed', models.CharField(choices=[('slow', 'Slow Learner'), ('average', 'Average Learner'), ('fast', 'Fast Learner')], default='average', help_text='Calculated learning speed based on performance', max_length=20)),
                ('preferred_explanation_mode', models.CharField(choices=[('visual', 'Visual First'), ('text', 'Text First'), ('mixed', 'Mixed Mode')], default='visual', help_text="Student's preferred way of receiving explanations", max_length=20)),
                ('error_patterns', models.JSONField(blank=True, default=dict, help_text='JSON tracking common error types and frequencies')),
                ('weak_concepts', models.JSONField(blank=True, default=list, help_text='List of concept IDs where student struggles')),
                ('strong_concepts', models.JSONField(blank=True, default=list, help_text='List of concept IDs where student excels')),
                ('total_mastery_points', models.IntegerField(default=0, help_text='Cumulative mastery points across all lessons', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_streak_days', models.IntegerField(default=0, help_text='Current consecutive days of learning', validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak_days', models.IntegerField(default=0, help_text='Longest streak ever achieved', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_date', models.DateField(blank=True, help_text='Date of last learning activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Learning Profile',
                'verbose_name_plural': 'Student Learning Profiles',
            },
        ),
        migrations.CreateModel(
            name='DifficultyCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject for this calibration', max_length=50)),
                ('current_difficulty', models.CharField(choices=[('support', 'Support Level'), ('core', 'Core Level'), ('challenge', 'Challenge Level')], default='core', help_text='Current difficulty level for this student/subject', max_length=20)),
                ('rolling_accuracy', models.FloatField(default=0.5, help_text='Rolling accuracy over last 20 questions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_time_per_question', models.FloatField(default=60.0, help_text='Average time per question in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_retries', models.FloatField(default=0.0, help_text='Average retries per question', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recent_attempts', models.JSONField(default=list, help_text='Last 20 attempt results for rolling calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student being calibrated', on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_calibrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Difficulty Calibration',
                'verbose_name_plural': 'Difficulty Calibrations',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['lesson_id'], name='learning_en_lesson__d757ab_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['subject', 'class_number'], name='learning_en_subject_7ba77d_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['chapter_id', 'sequence_in_chapter'], name='learning_en_chapter_71927b_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['qa_status', 'is_published'], name='learning_en_qa_stat_4806fa_idx'),
        ),
        migrations.AddIndex(
            model_name='microlessonprogress',
            index=models.Index(fields=['student', 'status'], name='learning_en_student_e0e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='microlessonprogress',
            index=models.Index(fields=['micro_lesson', 'status'], name='learning_en_micro_l_328fe5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='microlessonprogress',
            unique_together={('student', 'micro_lesson', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['lesson_progress', 'question_index'], name='learning_en_lesson__84d80d_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceattempt',
            index=models.Index(fields=['is_correct'], name='learning_en_is_corr_32361f_idx'),
        ),
    ]
