# Generated by Django 5.2.7 on 2026-02-12 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(help_text='Unique lesson ID (e.g., ENG1_MRIDANG_01)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('subject', models.CharField(help_text='Subject (Math, Science, English, etc.)', max_length=50)),
                ('class_number', models.IntegerField(help_text='Class/Grade number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('chapter_id', models.CharField(help_text='Chapter identifier', max_length=50)),
                ('chapter_name', models.CharField(help_text='Chapter name', max_length=200)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives for this lesson')),
                ('total_duration_minutes', models.IntegerField(default=35, help_text='Total duration for all 5 micro-lessons (typically 35-50 minutes)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Teaching'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Lesson status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.AlterModelOptions(
            name='microlesson',
            options={'ordering': ['lesson', 'sequence_in_lesson'], 'verbose_name': 'Micro-Lesson', 'verbose_name_plural': 'Micro-Lessons'},
        ),
        migrations.RemoveIndex(
            model_name='microlesson',
            name='learning_en_lesson__d757ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='microlesson',
            name='learning_en_subject_7ba77d_idx',
        ),
        migrations.RemoveIndex(
            model_name='microlesson',
            name='learning_en_chapter_71927b_idx',
        ),
        migrations.AddField(
            model_name='microlesson',
            name='concept_explanation',
            field=models.TextField(blank=True, default='', help_text='Clear concept explanation in ≤120 words, age-appropriate, jargon-free', max_length=800),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='difficulty_level',
            field=models.CharField(choices=[('support', 'Support Level'), ('core', 'Core Level'), ('challenge', 'Challenge Level')], default='core', help_text='Difficulty level for adaptive learning', max_length=20),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='learner_action',
            field=models.JSONField(blank=True, default=dict, help_text='Active learning task aligned to the concept'),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='micro_lesson_id',
            field=models.CharField(default='', help_text='Unique micro-lesson ID (e.g., MATH_C5_CH3_ML2)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='reinforcement_summary',
            field=models.TextField(blank=True, default='', help_text='Concise reinforcement summary restating core idea (≤50 words)', max_length=350),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='sequence_in_lesson',
            field=models.IntegerField(default=1, help_text='Sequence of this micro-lesson within the lesson (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='validation_logic',
            field=models.JSONField(blank=True, default=dict, help_text='AI validation rules and feedback logic'),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='worked_example',
            field=models.JSONField(blank=True, default=dict, help_text='Worked example with problem statement and step-by-step solution'),
        ),
        migrations.AlterField(
            model_name='microlesson',
            name='visual_assets',
            field=models.JSONField(blank=True, default=list, help_text='Supporting visual assets for this micro-lesson'),
        ),
        migrations.AddField(
            model_name='microlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Parent lesson that contains this micro-lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_lessons', to='learning_engine.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='microlesson',
            unique_together={('lesson', 'sequence_in_lesson')},
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['micro_lesson_id'], name='learning_en_micro_l_78b479_idx'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['lesson', 'sequence_in_lesson'], name='learning_en_lesson__37d791_idx'),
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='chapter_id',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='learning_objective',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='misconceptions',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='practice_questions',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='practice_themes',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='sequence_in_chapter',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='teacher_narration',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='textbook_reading',
        ),
        migrations.RemoveField(
            model_name='microlesson',
            name='worked_examples',
        ),
    ]
