# Generated by Django 5.2.7 on 2026-02-14 02:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_engine', '0002_lesson_alter_microlesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(help_text='Date of this activity record')),
                ('concepts_completed', models.IntegerField(default=0, help_text='Number of concepts/micro-lessons completed this day', validators=[django.core.validators.MinValueValidator(0)])),
                ('questions_answered', models.IntegerField(default=0, help_text='Number of questions answered this day', validators=[django.core.validators.MinValueValidator(0)])),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent learning in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('qualifies_as_learning_day', models.BooleanField(default=False, help_text='True if >= 1 concept completed OR >= 10 questions answered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student whose activity is tracked', on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['student', 'activity_date'], name='learning_en_student_217c07_idx')],
                'unique_together': {('student', 'activity_date')},
            },
        ),
    ]
