# Generated by Django 5.2.7 on 2026-02-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('read_along_service', '0002_seed_languages'),
        ('teaching_engine', '0003_dayprogress_comprehension_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readalongsession',
            name='unique_read_along_attempt',
        ),
        migrations.AlterUniqueTogether(
            name='readalongsession',
            unique_together={('student', 'lesson', 'day_number', 'language', 'attempt_number')},
        ),
    ]
