"""
2026-02-20: Badge catalog and cosmetic items for Gamification Engine (BS-GAM).

BADGE_CATALOG: 20 achievement badges with criteria descriptions.
COSMETIC_ITEMS: 6 purchasable cosmetic items (stub for BS-GAM-003).
"""

# 2026-02-20: 20 badge definitions. Each entry matches Badge model fields.
# criterion_* fields are NOT stored in DB — they guide badge_service.py logic.
BADGE_CATALOG = [
    # ── Learning badges ─────────────────────────────────────────────────────
    {
        'badge_id': 'first_step',
        'name': 'First Step',
        'description': 'Complete your very first lesson day.',
        'icon': '👣',
        'category': 'learning',
        'rarity': 'common',
        'criterion_type': 'day_progress_count',
        'criterion_value': 1,
    },
    {
        'badge_id': 'quick_learner',
        'name': 'Quick Learner',
        'description': 'Complete 3 lesson days in a single day.',
        'icon': '⚡',
        'category': 'learning',
        'rarity': 'common',
        'criterion_type': 'day_progress_today',
        'criterion_value': 3,
    },
    {
        'badge_id': 'dedicated_student',
        'name': 'Dedicated Student',
        'description': 'Complete 20 lesson days total.',
        'icon': '📚',
        'category': 'learning',
        'rarity': 'uncommon',
        'criterion_type': 'day_progress_count',
        'criterion_value': 20,
    },
    {
        'badge_id': 'super_scholar',
        'name': 'Super Scholar',
        'description': 'Complete 100 lesson days total.',
        'icon': '🎓',
        'category': 'learning',
        'rarity': 'rare',
        'criterion_type': 'day_progress_count',
        'criterion_value': 100,
    },
    # ── Streak badges ────────────────────────────────────────────────────────
    {
        'badge_id': 'first_flame',
        'name': 'First Flame',
        'description': 'Start your first learning streak.',
        'icon': '🔥',
        'category': 'streak',
        'rarity': 'common',
        'criterion_type': 'streak',
        'criterion_value': 1,
    },
    {
        'badge_id': 'on_a_roll',
        'name': 'On a Roll',
        'description': 'Maintain a 3-day streak.',
        'icon': '🎳',
        'category': 'streak',
        'rarity': 'common',
        'criterion_type': 'streak',
        'criterion_value': 3,
    },
    {
        'badge_id': 'week_warrior',
        'name': 'Week Warrior',
        'description': 'Maintain a 7-day streak.',
        'icon': '🏆',
        'category': 'streak',
        'rarity': 'uncommon',
        'criterion_type': 'streak',
        'criterion_value': 7,
    },
    {
        'badge_id': 'fortnight_force',
        'name': 'Fortnight Force',
        'description': 'Maintain a 14-day streak.',
        'icon': '💪',
        'category': 'streak',
        'rarity': 'uncommon',
        'criterion_type': 'streak',
        'criterion_value': 14,
    },
    {
        'badge_id': 'monthly_hero',
        'name': 'Monthly Hero',
        'description': 'Maintain a 30-day streak.',
        'icon': '🦸',
        'category': 'streak',
        'rarity': 'rare',
        'criterion_type': 'streak',
        'criterion_value': 30,
    },
    # ── Star badges ──────────────────────────────────────────────────────────
    {
        'badge_id': 'shooting_star',
        'name': 'Shooting Star',
        'description': 'Earn a perfect 5-star rating.',
        'icon': '🌠',
        'category': 'stars',
        'rarity': 'common',
        'criterion_type': 'practice_5star_count',
        'criterion_value': 1,
    },
    {
        'badge_id': 'star_collector',
        'name': 'Star Collector',
        'description': 'Earn 25 stars total.',
        'icon': '⭐',
        'category': 'stars',
        'rarity': 'common',
        'criterion_type': 'total_stars',
        'criterion_value': 25,
    },
    {
        'badge_id': 'star_champion',
        'name': 'Star Champion',
        'description': 'Earn 100 stars total.',
        'icon': '🌟',
        'category': 'stars',
        'rarity': 'rare',
        'criterion_type': 'total_stars',
        'criterion_value': 100,
    },
    {
        'badge_id': 'perfect_week',
        'name': 'Perfect Week',
        'description': 'Earn 5 stars every day for 7 days in a row.',
        'icon': '✨',
        'category': 'stars',
        'rarity': 'epic',
        'criterion_type': 'practice_5star_last7',
        'criterion_value': 7,
    },
    # ── Vocabulary badges ────────────────────────────────────────────────────
    {
        'badge_id': 'word_seeker',
        'name': 'Word Seeker',
        'description': 'Master 5 vocabulary words.',
        'icon': '🔍',
        'category': 'vocabulary',
        'rarity': 'common',
        'criterion_type': 'vocab_mastered',
        'criterion_value': 5,
    },
    {
        'badge_id': 'vocabulary_builder',
        'name': 'Vocabulary Builder',
        'description': 'Master 25 vocabulary words.',
        'icon': '📖',
        'category': 'vocabulary',
        'rarity': 'uncommon',
        'criterion_type': 'vocab_mastered',
        'criterion_value': 25,
    },
    {
        'badge_id': 'linguist',
        'name': 'Linguist',
        'description': 'Master 100 vocabulary words.',
        'icon': '🗣️',
        'category': 'vocabulary',
        'rarity': 'rare',
        'criterion_type': 'vocab_mastered',
        'criterion_value': 100,
    },
    {
        'badge_id': 'multilingual',
        'name': 'Multilingual',
        'description': 'Complete vocabulary sessions in 2 or more languages.',
        'icon': '🌍',
        'category': 'vocabulary',
        'rarity': 'uncommon',
        'criterion_type': 'vocab_languages',
        'criterion_value': 2,
    },
    # ── Reading badges ───────────────────────────────────────────────────────
    {
        'badge_id': 'story_starter',
        'name': 'Story Starter',
        'description': 'Complete your first read-along session.',
        'icon': '📕',
        'category': 'reading',
        'rarity': 'common',
        'criterion_type': 'read_along_count',
        'criterion_value': 1,
    },
    {
        'badge_id': 'reading_champion',
        'name': 'Reading Champion',
        'description': 'Complete 10 read-along sessions.',
        'icon': '📗',
        'category': 'reading',
        'rarity': 'uncommon',
        'criterion_type': 'read_along_count',
        'criterion_value': 10,
    },
    {
        'badge_id': 'bookworm',
        'name': 'Bookworm',
        'description': 'Complete 25 read-along sessions.',
        'icon': '🐛',
        'category': 'reading',
        'rarity': 'rare',
        'criterion_type': 'read_along_count',
        'criterion_value': 25,
    },
]

# 2026-02-20: Cosmetic items available for purchase with coins (stub for BS-GAM-003).
COSMETIC_ITEMS = {
    'avatar_star': {'name': 'Star Explorer Frame', 'cost': 50},
    'avatar_space': {'name': 'Space Cadet Frame', 'cost': 75},
    'theme_forest': {'name': 'Forest Theme', 'cost': 100},
    'theme_space': {'name': 'Space Theme', 'cost': 100},
    'frame_gold': {'name': 'Gold Badge Frame', 'cost': 150},
    'flame_blue': {'name': 'Blue Flame Icon', 'cost': 200},
}
