# Generated by Django 5.2.7 on 2026-02-17 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(help_text='e.g. ENG1_MRIDANG_W01', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('class_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('chapter_id', models.CharField(blank=True, max_length=50)),
                ('chapter_title', models.CharField(blank=True, max_length=200)),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('character_name', models.CharField(blank=True, default='', max_length=100)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('content_json_path', models.CharField(help_text='Relative path from project root to content JSON', max_length=500)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_number', 'subject', 'week_number'],
                'indexes': [models.Index(fields=['class_number', 'subject'], name='teaching_en_class_n_0dd299_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iq_level', models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', max_length=20)),
                ('current_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('day_statuses', models.JSONField(blank=True, default=dict, help_text='e.g. {"1":"completed","2":"in_progress","3":"not_started"}')),
                ('total_score', models.IntegerField(default=0)),
                ('assessment_score', models.IntegerField(blank=True, null=True)),
                ('assessment_star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_progress', to='auth_service.student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='teaching_engine.teachinglesson')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('messages', models.JSONField(blank=True, default=list, help_text='[{"role":"student","text":"...","ts":"..."},{"role":"mentor",...}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='teaching_engine.studentlessonprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='auth_service.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('revision', 'In Revision'), ('teaching', 'In Teaching'), ('practice', 'In Practice'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('revision_completed', models.BooleanField(default=False)),
                ('practice_score', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_records', to='teaching_engine.studentlessonprogress')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('lesson_progress', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='e.g. {"WA_Q1": 0, "WA_Q2": 2}')),
                ('score', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='teaching_engine.studentlessonprogress')),
            ],
            options={
                'ordering': ['-attempt_number'],
                'unique_together': {('lesson_progress', 'attempt_number')},
            },
        ),
    ]
