# Generated by Django 5.2.7 on 2026-02-17 15:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('teaching_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayprogress',
            name='mastery_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayprogress',
            name='mastery_star_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dayprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('revision', 'In Revision'), ('teaching', 'In Teaching'), ('practice', 'In Practice'), ('mastery_practice', 'Mastery Practice'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('iq_level', models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('current_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('consecutive_incorrect', models.IntegerField(default=0)),
                ('same_difficulty_streak', models.IntegerField(default=0)),
                ('star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('percentage_correct', models.FloatField(default=0.0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=1)),
                ('administered_question_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='teaching_engine.studentlessonprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='auth_service.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lesson_progress', 'day_number', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('best_star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('attempts_count', models.IntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to='teaching_engine.teachinglesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_masteries', to='auth_service.student')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('student', 'lesson', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='PracticeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=100)),
                ('concept_id', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('numeric_fill', 'Numeric Fill'), ('drag_order', 'Drag and Order')], default='mcq', max_length=20)),
                ('student_answer', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='teaching_engine.practicesession')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('session', 'position')},
            },
        ),
    ]
