# Generated by Django 5.2.7 on 2026-02-12 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('theta_estimate', models.FloatField(default=0.0, help_text='Current IRT theta estimate, clamped to [-3, 3]')),
                ('items_administered', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=25)),
                ('result_level', models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='', max_length=20)),
                ('domain_scores', models.JSONField(blank=True, default=dict, help_text='Dict of domain -> theta, e.g. {"math": 0.5, "language": -0.2}')),
                ('current_item_id', models.CharField(blank=True, default='', max_length=50)),
                ('administered_item_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='auth_service.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_level', models.CharField(choices=[('foundation', 'Foundation'), ('standard', 'Standard'), ('advanced', 'Advanced')], max_length=20)),
                ('theta_final', models.FloatField()),
                ('domain_levels', models.JSONField(blank=True, default=dict, help_text='Dict of domain -> level, e.g. {"math": "advanced"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_result', to='auth_service.student')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='diagnostic_service.diagnosticsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField(default=0)),
                ('theta_after', models.FloatField(default=0.0)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='diagnostic_service.diagnosticsession')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
